namespace MenaceCharacterInstaller;
public static class Localize
{
    public static string Language {get;set;}="ru";
    public static readonly IReadOnlyDictionary<string,(string Ru,string En)> Strings=new Dictionary<string,(string,string)>
    {
        ["subtitle"]=("Выберите пак и соберите свой отряд","Choose a pack and build your roster"),
        ["game"]=("01 / ПАПКА ИГРЫ","01 / GAME FOLDER"),
        ["detect"]=("Найти","Detect"),["browse"]=("Обзор…","Browse…"),["check"]=("Проверить","Check"),
        ["source"]=("02 / ИСТОЧНИК ПЕРСОНАЖЕЙ","02 / CHARACTER SOURCE"),
        ["openzip"]=("Открыть ZIP…","Open ZIP…"),["bundled"]=("Встроенный пак","Bundled pack"),
        ["roster"]=("03 / ПЕРСОНАЖИ","03 / CHARACTERS"),
        ["all"]=("Все","Select all"),["none"]=("Снять","Clear"),
        ["search"]=("Поиск по имени, отряду или описанию","Search by name, unit or description"),
        ["gamepath"]=("Папка MENACE","MENACE folder"),["archivepath"]=("Исходный ZIP","Source ZIP"),
        ["allow"]=("Разрешить установку на непроверенную версию игры","Allow installation on an unverified game build"),
        ["cancel"]=("Отмена","Cancel"),["restore"]=("Откат","Restore"),["install"]=("Установить выбранных","Install selected"),
        ["mods"]=("Папка Mods","Mods folder"),["logs"]=("Журнал","Logs"),
        ["footer"]=("Загрузчики из официальных источников · Данные не отправляются","Official loader downloads · No telemetry"),
        ["campaign"]=("Выбор заменяет состав этого пака. Сохраняйте в выборе персонажей существующей кампании.","Selection replaces this pack's roster. Keep characters used by existing campaigns selected."),
        ["loading"]=("Загрузка каталога…","Loading catalogue…"),["importing"]=("Чтение пака и извлечение портретов…","Reading pack and extracting portraits…"),
        ["infantry"]=("Пехота","Infantry"),["vehicle"]=("Экипаж техники","Vehicle crew"),
        ["replacement"]=("Замена","Replacement"),["installed"]=("Установлен","Installed"),
        ["missing"]=("Не установлен / требуется обновление","Missing / update required"),
        ["download"]=("Скачать ↗","Download ↗"),["auto"]=("Автоустановка","Automatic install"),
        ["depinstall"]=("Установить","Install"),["website"]=("Сайт ↗","Website ↗"),
        ["depautohint"]=("Скачать и установить автоматически. Установщик .NET откроется отдельно.","Download and install automatically. The .NET setup wizard opens separately."),
        ["deplocalhint"]=("Установить из скачанного ZIP или DLL. Страница автора доступна по кнопке «Сайт».","Install from a downloaded ZIP or DLL. Use Website to open the author's download page."),
        ["depchoose"]=("Выберите скачанный файл: {0}","Choose the downloaded file: {0}"),
        ["depfilter"]=("Архив или DLL мода (*.zip;*.dll)|*.zip;*.dll","Mod ZIP or DLL (*.zip;*.dll)|*.zip;*.dll"),
        ["depstarting"]=("Скачивание и установка: {0}…","Downloading and installing: {0}…"),
        ["depdone"]=("{0} установлен. Индикаторы обновлены.","{0} installed. Indicators updated."),
        ["depready"]=("{0} уже установлен.","{0} is already installed."),
        ["deprestart"]=("{0}: установка завершена. Перезагрузите Windows перед игрой.","{0}: setup completed. Restart Windows before playing."),
        ["manual"]=("Скачайте и установите, затем нажмите «Проверить».","Download and install, then click Check."),
        ["selected"]=("Выбрано {0} / {1}","Selected {0} / {1}"),
        ["choosegame"]=("Укажите папку MENACE.","Choose the MENACE folder."),
        ["manygames"]=("Найдено несколько установок. Выберите папку игры.","Multiple installations found. Choose the game folder."),
        ["known"]=("{0} · проверенная сборка","{0} · verified build"),
        ["unverified"]=("Совместимость не проверена · игра {0}","Compatibility unverified · game {0}"),
        ["notinstalled"]=("Не установлен","Not installed"),["unknown"]=("Неизвестно","Unknown"),
        ["checked"]=("Проверка завершена. Отметьте персонажей для установки.","Check complete. Select characters to install."),
        ["choosefolder"]=("Выберите папку, в которой находится Menace.exe","Choose the folder containing Menace.exe"),
        ["choosezip"]=("Выберите скачанный ZIP с персонажами","Choose a downloaded character-pack ZIP"),
        ["zipfilter"]=("Паки персонажей ZIP (*.zip)|*.zip","Character pack ZIP (*.zip)|*.zip"),
        ["loaded"]=("Пак загружен: {0} персонажей.","Pack loaded: {0} characters."),
        ["packinfo"]=("{0} · версия {1} · {2} · {3} персонажей","{0} · version {1} · {2} · {3} characters"),
        ["pickone"]=("Выберите хотя бы одного персонажа.","Select at least one character."),
        ["unverifiederror"]=("Эта сборка игры не проверена. Нажмите «Проверить» и ознакомьтесь с предупреждением.","This game build is unverified. Click Check and review the notice."),
        ["installtitle"]=("Установка выбранных персонажей","Install selected characters"),
        ["installnames"]=("Установить: {0}.\n\n","Install: {0}.\n\n"),
        ["removenames"]=("Будут убраны из этого пака: {0}. Не загружайте кампании с ними до их возврата.\n\n","Removed from this pack: {0}. Do not load campaigns using them until they are restored.\n\n"),
        ["downloadnames"]=("Скачать и установить автоматически: {0}.\n\n","Download and install automatically: {0}.\n\n"),
        ["readydeps"]=("Все зависимости установлены.\n\n","All dependencies are installed.\n\n"),
        ["confirm"]=("Резервная копия файлов игры будет сохранена для отката. Системный .NET при откате не удаляется. Продолжить?","Game files will be backed up for restore. The system .NET runtime remains installed after restore. Continue?"),
        ["done"]=("Готово: {0} персонажей. Запустите MENACE и начните новую кампанию.","Done: {0} characters. Start MENACE and begin a new campaign."),
        ["cancelled"]=("Подготовка отменена. Файлы игры не изменены.","Preparation cancelled. Game files have not changed."),
        ["cancelpending"]=("Отмена запрошена. Если запись уже началась, она завершится безопасно.","Cancellation requested. If file writes have started, they will finish safely."),
        ["nobackup"]=("Для этой папки игры нет установки, которую можно откатить.","No installation is available to restore for this game folder."),
        ["restoreconfirm"]=("Вернуть файлы игры к состоянию перед последней установкой? Системный .NET останется установленным.","Restore game files to their state before the last installation? The system .NET runtime will remain installed."),
        ["restored"]=("Предыдущая установка восстановлена.","Previous installation restored."),
        ["wait"]=("Дождитесь завершения операции или отмените подготовку.","Wait for the operation to finish or cancel preparation."),
        ["failed"]=("Не удалось завершить действие. Подробности в журнале.","Could not complete the action. Details are in the log."),
        ["detailerror"]=("Не удалось выполнить действие. Технические подробности:\n{0}","Could not complete the action. Technical details:\n{0}"),
        ["alreadyrunning"]=("MENACE Character Installer уже запущен.","MENACE Character Installer is already running."),
        ["imported_compatibility"]=("Совместимость внешнего пака с вашей версией игры не проверена.","This external pack's compatibility with your game build is unverified."),
        ["shared_resources"]=("Общие ресурсы пака сохраняются; в игру добавляются только выбранные персонажи.","Shared pack resources are retained; only selected characters are registered in the game."),
        ["global_changes"]=("Пак содержит общие изменения игры; они сохраняются при любом выборе персонажей.","This pack includes global game changes, retained with every character selection."),
        ["linked_characters"]=("Связанные персонажи выбираются вместе, чтобы сохранить их зависимости.","Linked characters are selected together to preserve their dependencies."),
        ["missing_portraits"]=("Часть портретов не удалось извлечь. Эти персонажи доступны для выбора.","Some portraits could not be extracted. Those characters can still be selected."),
        ["legacy_voice"]=("Озвучка из voice_manifest.json требует отдельной поддержки загрузчика.","Voice settings in voice_manifest.json require additional loader support."),
        ["agility"]=("Ловкость","Agility"),["weapon_skill"]=("Навык оружия","Weapon skill"),["valour"]=("Храбрость","Valour"),
        ["toughness"]=("Стойкость","Toughness"),["vitality"]=("Живучесть","Vitality"),["precision"]=("Точность","Precision"),["positioning"]=("Позиционирование","Positioning"),
        ["missingpreview"]=("Портрет недоступен","Portrait unavailable"),
        ["pickable"]=("All Leaders Pickable также добавляет стандартных лидеров в стартовый список.","All Leaders Pickable also adds vanilla leaders to the starting roster."),
    };
    public static string T(string key,params object[] args)
    {var pair=Strings[key];return string.Format(Language=="en"?pair.En:pair.Ru,args);}
    public static string Diagnostic(string message)
    {
        if(Language=="en")return message;
        if(message.Any(c=>c>='\u0400'&&c<='\u04ff'))return message;
        foreach(var (en,ru) in Diagnostics)if(message.StartsWith(en,StringComparison.Ordinal))return ru+message[en.Length..];
        return T("detailerror",message);
    }
    private static readonly (string En,string Ru)[] Diagnostics=[
        ("Choose the MENACE folder containing Menace.exe, GameAssembly.dll and Menace_Data.","Выберите папку MENACE, содержащую Menace.exe, GameAssembly.dll и Menace_Data."),
        ("Close MENACE before installing or restoring files.","Закройте MENACE перед установкой или откатом."),
        ("Only ZIP character packs are supported.","Поддерживаются только паки персонажей в формате ZIP."),
        ("This archive contains several Jiangyu modules. Open a single character-pack module.","В архиве несколько модулей Jiangyu. Выберите архив одного пака персонажей."),
        ("No Jiangyu or Custom Leaders character definitions were found in this ZIP.","В ZIP нет персонажей в формате Jiangyu или Custom Leaders."),
        ("Code-based packs cannot be split safely by this installer.","Пак содержит DLL или EXE: выбор отдельных персонажей из такого архива не поддерживается."),
        ("This pack contains global mesh/texture replacements that cannot be assigned safely to individual characters.","Выбор отдельных персонажей из пака с общими заменами моделей или текстур не поддерживается."),
        ("This Jiangyu module has no selectable UnitLeaderTemplate definitions.","В модуле Jiangyu нет персонажей для выбора."),
        ("Install missing dependencies from their download pages, then click Check: ","Установите недостающие зависимости со страниц скачивания и нажмите «Проверить»: "),
        ("Install missing dependencies using their Install buttons: ","Установите недостающие зависимости кнопками «Установить»: "),
        ("Select the downloaded dependency archive: ","Выберите скачанный архив зависимости: "),
        ("The selected archive does not contain a suitable MelonLoader installation.","В архиве нет подходящей версии MelonLoader."),
        ("The selected archive does not contain the required dependency version: ","В архиве нет нужной версии зависимости: "),
        ("The archive must contain exactly one matching dependency DLL.","В архиве должен быть ровно один DLL нужной зависимости."),
        ("Select a ZIP or DLL dependency file.","Выберите ZIP или DLL зависимости."),
        ("Wrong dependency file: ","Неверный файл зависимости: "),
        ("Unknown dependency: ","Неизвестная зависимость: "),
        ("Restart Windows to finish .NET installation, then retry the character installation.","Перезагрузите Windows, чтобы завершить установку .NET, затем повторите установку персонажей."),
        ("Unsupported pack dependency: ","Неподдерживаемая зависимость пака: "),
        ("Character folder already exists and is not managed by this pack: ","Папка персонажа уже существует и не принадлежит этому паку: "),
        ("Another installed pack contains the same characters: ","Другой установленный пак содержит этих же персонажей: "),
        ("Existing target folder is not the expected character-pack module.","Папка назначения не соответствует выбранному модулю персонажей."),
        ("This game build has not been verified. Review the compatibility notice before continuing.","Эта сборка игры не проверена. Ознакомьтесь с предупреждением о совместимости."),
        ("BepInEx detected. This installer supports MelonLoader; resolve the loader conflict first.","Обнаружен BepInEx. Установщик использует MelonLoader; сначала устраните конфликт загрузчиков."),
        ("An existing version.dll belongs to an unknown loader. It will not be overwritten.","Существующий version.dll принадлежит неизвестному загрузчику. Установка остановлена."),
        ("Preparing ","Подготовка "),
        ("Downloading ","Скачивание "),
        ("Installing Microsoft .NET 6 Desktop x64. Windows may ask for administrator approval.","Установка Microsoft .NET 6 Desktop x64. Windows может запросить права администратора."),
        ("Installing ","Установка "),
        ("Installed ","Установлено "),
        ("Microsoft runtime requests a Windows restart before playing.","Microsoft .NET требует перезагрузки Windows перед игрой."),
        ("Runtime installation could not be verified. Restart Windows and try again.","Не удалось подтвердить установку .NET. Перезагрузите Windows и повторите попытку."),
        ("The game was updated while preparing this installation. Check compatibility again.","Игра обновилась во время подготовки установки. Проверьте совместимость снова."),
        ("File changed since this installation; restore stopped: ","После установки файл изменился; откат остановлен: "),
        ("External change prevents rollback: ","Внешнее изменение препятствует откату: "),
        ("File changed during installation: ","Файл изменился во время установки: "),
        ("File changed while backing up: ","Файл изменился во время резервного копирования: "),
        ("Backup belongs to another game","Резервная копия принадлежит другой игре"),
        ("Damaged backup","Повреждённая резервная копия"),
        ("Archive exceeds installation limits","Архив превышает ограничения установщика"),
        ("Duplicate archive entry: ","Повторяющийся файл в архиве: "),
        ("Unsafe relative path: ","Недопустимый относительный путь: "),
        ("Path escapes root","Путь выходит за пределы папки"),
        ("Symbolic links/junctions are not supported: ","Символические ссылки и junction не поддерживаются: "),
        ("Missing or damaged content. Extract the complete installer ZIP again: ","Файл отсутствует или повреждён. Распакуйте установщик целиком снова: "),
        ("Download integrity check failed: ","Проверка целостности скачанного файла не пройдена: "),
        ("Duplicate or unsafe character folder: ","Повторяющееся или недопустимое имя папки персонажа: "),
        ("Missing clone_from: ","Не задана игровая база clone_from: "),
        ("Linked characters must be selected together: ","Связанных персонажей нужно выбирать вместе: "),
        ("Choose at least one known character","Выберите хотя бы одного персонажа"),
    ];
}
