<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup><ItemGroup><PackageReference Include="AssetsTools.NET" Version="3.0.5"/><PackageReference Include="AssetsTools.NET.Texture" Version="3.0.2"/><PackageReference Include="StbImageWriteSharp" Version="1.16.7"/></ItemGroup></Project>
